#基础设置
spring:
  application:
    name: futureService
    #  数据设置
  datasource:
    name: test
    url: jdbc:mysql://127.0.0.1:3306/haiting?useUnicode=true&characterEncoding=utf8&allowMultiQueries=true&serverTimezone=GMT%2B8
    username: root
    password: 123456
    # 使用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    filters: stat
    maxActive: 20
    initialSize: 1
    maxWait: 60000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20
    # redis配置
  redis:
    host: 127.0.0.1
    port: 6397
    password:
    jedis:
      pool:
        max-active: 16
        max-idle: 8
        min-idle: 0
    timeout: 1000

#端口设置
server:
  port: 7075

#注册中心
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/


#pagehelper分页插件
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql

## 该配置节点为独立的节点，有很多同学容易将这个配置放在spring的节点下，导致配置无法被识别
mybatis:
  mapper-locations: classpath:mapping/*.xml  #注意：一定要对应mapper映射xml文件的所在路径
  type-aliases-package: com.future.entity  # 注意：对应实体类的路径

swagger:
  base-package: com.future.web
